### ISSUE TITLE
Unable to use AVAudioEngine.installTap() when using this repo

### ISSUE THREAD

**Issue by vinny-888** [Keith-43/MuVis-v2.1.1#1]
I am trying to record audio and stream it from the mic while also showing the wave form visualization.

Each work fine when the other is disabled but when both are enabled the Mic Audio stream coming from the AVAudioEngine stops working once the Waveform visualization is enabled.

I am guessing the BASS framework and AVAudioEngine are incompatible somehow.

Is there a way to get the mic data like you can in installTap() with Bass?

Any examples where both reading the mic audio stream and showing the waveform works at the same time?

**Comment by vinny-888** [comment]
I was able to get this working but had to connect a second BASS_ChannelGetData to get the right format

```swift
BASS_ChannelGetData(self.stream, &fullSpectrum, BASS_DATA_FFT16384)
                
let bytesRead = BASS_ChannelGetData(self.stream, &dataBuffer, 1024) // This is needed to get non FFT audio data
                
if bytesRead > 0 {
  let data = Data(bytes: dataBuffer, count: Int(bytesRead))
  // Process the raw data in dataBuffer
}
```

The mic recording is working now and the wave form is playing at the same time which is great!

On the playback side however I am not able to get the waveform to play when I use the following code to play the audio data

```swift
data.withUnsafeBytes { (bytes: UnsafeRawBufferPointer) -> Void in
    stream = BASS_StreamCreateFile(1, bytes.baseAddress, 0, QWORD(Int64(data.count)), 0)
    
    if stream == 0 {
        print("Error creating stream")
    } else {
        BASS_ChannelPlay(stream, 0)
    }
}
```

When I play a file from a path the wave form plays fine tho

```swift
stream = BASS_StreamCreateFile( BOOL32(truncating: false),  // mem: false = stream file from a filename
                                filePath,                   // file:
                                0,                          // offset:
                                0,                          // length: 0 = use all data up to end of file
                                0)                          // flags:

BASS_ChannelPlay(stream, -1) // starts the output
```

**Comment by vinny-888** [comment]
The sample file that works is 44100 Hz

The audio I am trying to play is 24000 Hz

I tried changing this but no change the waveform still fails to display anything

```swift
// Initialize the output device (i.e., speakers) that BASS should use:
BASS_Init(  -1,                                 // device: -1 is the default device; 0 is no sound output
             UInt32(24000),   // freq: output sample rate is 44,100 sps
             0,                                 // flags: DWORD
             nil,                               // win: 0 = the desktop window (for console applications)
             nil)                               // dsguid: Unused, set to nil
```

**Comment by vinny-888** [comment]
Turned out it was just that I needed to call it from the main thread (facepalm)

```swift
DispatchQueue.main.async {
  // Call the function here
}
```

I was testing the file play mode from 

```swift
init() {
  processAudio()
  }
  ```

**Comment by Keith-43** [comment]
Vinny,
	Thank you for keeping me updated on your experimentation with MuVis.  You know more about BASS than I do.  I am pleased that you apparently have solved all of your issues for now.  If more issues arise, I suggest you post them on the BASS Forum, where the moderator (Ian) is very good at answering specific questions and solving specific issues.

	If you wish to correspond with me directly, you can reach me at kbromley at me dot com.  (I suspect that the GitHub message router strips email addresses from messages.)

Keith
***@***.*** ***@***.***>

-------------------------
On Nov 30, 2023, at 11:01 PM, vinny-888 ***@***.***> wrote:
Turned out it was just that I needed to call it from the main thread (facepalm)

DispatchQueue.main.async {
  // Call the function here
}
I was testing the file play mode from

init() {
  processAudio()
  }
